services:
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # this is the address that kafka allows others to connect via it
      # set kafka if you are connecting via docker and set localhost if you are producing via java
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  clickhouse:
    image: bitnami/clickhouse:25.5.1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  cassandra:
    image: bitnami/cassandra:5.0.4
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_PASSWORD_SEEDER: "no"
      CASSANDRA_AUTHENTICATOR: "AllowAllAuthenticator"
      CASSANDRA_AUTHORIZER: "AllowAllAuthorizer"
    volumes:
      - cassandra_data:/var/lib/cassandra

  cockroachdb:
    image: docker pull cockroachdb/cockroach:v24.3.14
    ports:
      - "26257:26257"
      - "8082:8080"
    command: start-single-node --insecure
    volumes:
      - cockroach_data:/cockroach/cockroach-data

  log-generator:
    build:
      context: ./log-generator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  log-drain:
    build:
      context: ./log-drain
      dockerfile: Dockerfile
    depends_on:
      - kafka

  clickhouse-writer:
    build:
      context: ./clickhouse-writer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - clickhouse

  cassandra-writer:
    build:
      context: ./cassandra-writer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - cassandra

  rest-api:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - clickhouse
      - cassandra
      - cockroachdb

  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - rest-api

volumes:
  clickhouse_data:
  cassandra_data:
  cockroach_data:
  grafana_data:
