version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - log-analyzer-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - log-analyzer-network

  clickhouse:
    image: bitnami/clickhouse:25.5.1
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      ALLOW_EMPTY_PASSWORD: true
    networks:
      - log-analyzer-network

  cassandra:
    image: bitnami/cassandra:5.0.4
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_PASSWORD_SEEDER: "no"
      CASSANDRA_AUTHENTICATOR: "AllowAllAuthenticator"
      CASSANDRA_AUTHORIZER: "AllowAllAuthorizer"
    networks:
      - log-analyzer-network

  cockroachdb:
    image: cockroachdb/cockroach:v24.3.14
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8082:8080"
    command: start-single-node --insecure
    networks:
      - log-analyzer-network

  log-generator:
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        - MODULE=log-generator
    ports:
      - "8084:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    networks:
      - log-analyzer-network

  log-drain:
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        - MODULE=log-drain
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - log-analyzer-network

  clickhouse-writer:
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        - MODULE=clickhouse-writer
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CLICKHOUSE_HOST=clickhouse
    depends_on:
      - clickhouse
    networks:
      - log-analyzer-network

  cassandra-writer:
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        - MODULE=cassandra-writer
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CASSANDRA_HOST=cassandra
    depends_on:
      - cassandra
    networks:
      - log-analyzer-network

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        - MODULE=rest-api
    ports:
      - "8081:8081"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CASSANDRA_HOST=cassandra
      - COCKROACH_HOST=cockroachdb
    networks:
      - log-analyzer-network

  gui:
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        - MODULE=gui
    ports:
      - "8083:8083"
    environment:
      - REST_API_HOST=rest-api
    networks:
      - log-analyzer-network

networks:
  log-analyzer-network:
    driver: bridge
